// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: user.proto

package server

import (
	"context"

	"go_zero/learn1/test2/user/rpc/internal/logic"
	"go_zero/learn1/test2/user/rpc/internal/svc"
	"go_zero/learn1/test2/user/rpc/types/user"
)

type UserInfoServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserInfoServer
}

func NewUserInfoServer(svcCtx *svc.ServiceContext) *UserInfoServer {
	return &UserInfoServer{
		svcCtx: svcCtx,
	}
}

func (s *UserInfoServer) GetUserInfo(ctx context.Context, in *user.UserInfoReq) (*user.UserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}
