// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type CreateOrderReq struct {
	UserID  int64 `json:"user_id"`
	OrderID int64 `json:"order_id"`
}

type CreateOrderResp struct {
	Message string `json:"message"`
}

type SearchReq struct {
	OrderID int64 `form:"order_id"`
}

type SearchResp struct {
	UserID   string `json:"user_id"`
	Status   int    `json:"status"`
	UserName string `json:"username"`
}
