// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: user.proto

package userinfo

import (
	"context"

	"go_zero/learn1/test2/user/rpc/types/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UserInfoReq  = user.UserInfoReq
	UserInfoResp = user.UserInfoResp

	UserInfo interface {
		GetUserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoResp, error)
	}

	defaultUserInfo struct {
		cli zrpc.Client
	}
)

func NewUserInfo(cli zrpc.Client) UserInfo {
	return &defaultUserInfo{
		cli: cli,
	}
}

func (m *defaultUserInfo) GetUserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoResp, error) {
	client := user.NewUserInfoClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}
